### ISSUE TITLE
Issue running Jellyfish with 'docker pull' from Docker Hub

### ISSUE THREAD

**Issue by watkinsc** [boozallen/projectjellyfish#1139]
**Backstory**
As I understand it, you can pull project jellyfish using the docker pull command found on the Jellyfish [docker hub](https://hub.docker.com/r/boozallen/projectjellyfish/) page. It seems that this pulls and runs the main application, following the steps found in the [Dockerfile](https://github.com/boozallen/projectjellyfish/blob/develop/Dockerfile). 

However, it doesn’t create the database (which I believe is a separate docker image created by commands in the docker-compose.yml). This causes the rails app to start, and immediately terminate since it can’t find a database to connect to.

I know if I was to just use Docker instead of docker-compose (and still cloning the source from github) I would need to modify the Dockerfile to contain a “DATABASE_URL”, as well as set up (and populate) my own database.

**Question**
Is there a way to have Jellyfish set up just by using a docker pull command? Meaning ‘docker pull mydockerhub/projectjellyfish’ would pull the image, create the database, and start the rails application (and avoid having to clone this repository).

I imagine it would require changes to the Dockerfile (as well as updating the existing docker image or creating my own docker image).

Container Log from `docker pull boozallen/projectjellyfish` below.
```
=> Booting Puma
=> Rails 4.2.3 application starting in docker on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `initialize': could not translate host name "db" to address: Name or service not known (PG::ConnectionBad)
from /usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `new'
from /usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `connect'
from /usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
from /usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
from /usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
from /usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
from /usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
from /usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
from /usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
from /usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
from /usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
from /usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
from /usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
from /usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
from /usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
from /usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
from /usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_handling.rb:87:in `connection'
from /usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/model_schema.rb:230:in `table_exists?'
from /api/config/initializers/jellyfish_core.rb:6:in `block in <top (required)>'
from /api/config/initializers/jellyfish_core.rb:5:in `each'
from /api/config/initializers/jellyfish_core.rb:5:in `<top (required)>'
from /usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
from /usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
from /usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
from /usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
from /usr/local/bundle/gems/railties-4.2.3/lib/rails/engine.rb:652:in `block in load_config_initializer'
from /usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/notifications.rb:166:in `instrument'
from /usr/local/bundle/gems/railties-4.2.3/lib/rails/engine.rb:651:in `load_config_initializer'
from /usr/local/bundle/gems/railties-4.2.3/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
from /usr/local/bundle/gems/railties-4.2.3/lib/rails/engine.rb:615:in `each'
from /usr/local/bundle/gems/railties-4.2.3/lib/rails/engine.rb:615:in `block in <class:Engine>'
from /usr/local/bundle/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `instance_exec'
from /usr/local/bundle/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `run'
from /usr/local/bundle/gems/railties-4.2.3/lib/rails/initializable.rb:55:in `block in run_initializers'
from /usr/local/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
from /usr/local/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
from /usr/local/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
from /usr/local/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
from /usr/local/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
from /usr/local/bundle/gems/railties-4.2.3/lib/rails/initializable.rb:44:in `each'
from /usr/local/bundle/gems/railties-4.2.3/lib/rails/initializable.rb:44:in `tsort_each_child'
from /usr/local/lib/ruby/2.3.0/tsort.rb:415:in `call'
from /usr/local/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
from /usr/local/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each'
from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `call'
from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
from /usr/local/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
from /usr/local/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
from /usr/local/bundle/gems/railties-4.2.3/lib/rails/initializable.rb:54:in `run_initializers'
from /usr/local/bundle/gems/railties-4.2.3/lib/rails/application.rb:352:in `initialize!'
from /api/config/environment.rb:5:in `<top (required)>'
from /usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
from /usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
from /usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
from /usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
from /api/config.ru:3:in `block in <main>'
from /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
from /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
from /api/config.ru:in `new'
from /api/config.ru:in `<main>'
from /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
from /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
from /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
from /usr/local/bundle/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
from /usr/local/bundle/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
from /usr/local/bundle/gems/railties-4.2.3/lib/rails/commands/server.rb:61:in `app'
from /usr/local/bundle/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
from /usr/local/bundle/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
from /usr/local/bundle/gems/railties-4.2.3/lib/rails/commands/server.rb:80:in `start'
from /usr/local/bundle/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:80:in `block in server'
from /usr/local/bundle/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:75:in `tap'
from /usr/local/bundle/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:75:in `server'
from /usr/local/bundle/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
from /usr/local/bundle/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
from bin/rails:4:in `require'
from bin/rails:4:in `<main>'
```

Let me know if I can provide any additional explanation, or if you have trouble reproducing this issue.

Thanks!

**Comment by chriskacerguis** [comment]
So, you can do a

```bash
docker pull boozallen/projectjellyfish
```

the repo is just to get the docker-compose.yml file.  You would still need to setup a DB container and populate it.  It is not considered a best pattern for having multiple services in one container.

We are working on addressing the one time db:setup needed.
