### ISSUE TITLE
'gulp build --production' fails locally

### ISSUE THREAD

**Issue by watkinsc** [boozallen/projectjellyfish#1140]
Steps to reproduce:

Assuming that all necessary tools are installed already (nodejs, gulp, bower etc.)

Clone repository: https://github.com/boozallen/projectjellyfish.git
From project base, run the following (same commands as contained in Dockerfile):
```
bundle install --without development test
npm install --production
bower install --allow-root --config.interactive=false
gulp build --production
```

All commands complete successfully until `gulp build --production`, which gives:
```
[13:49:00] Using gulpfile ~/projectjellyfish/gulpfile.js
[13:49:00] Starting 'wiredep'...
[13:49:00] Starting 'sass'...
[13:49:00] Starting 'templatecache'...
[13:49:00] Starting 'images'...
[13:49:00] Starting 'fonts'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: spawn /Users/christopherwatkins/Desktop/freshjf/testdock/projectjellyfish/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

Let me know if I can provide additional information.

Thanks!

**Comment by chriskacerguis** [comment]
We should have #1132 committed in a day or two, which will resolve this issue.  Closing ticket.
