### ISSUE TITLE
Rake Task failing in 'docker-compose up'

### ISSUE THREAD

**Issue by watkinsc** [boozallen/projectjellyfish#1163]
### Expected Behavior

`docker-compose up` should generate web/db container within docker successfully

### Current Behavior

`docker-compose up` currently fails on Step 15 in Dockerfile: `Step 15 : RUN DB_ADAPTER=nulldb bundle exec rake assets:precompile`

### Possible Solution

Given the trace below, it would appear it is looking for a library that does not exist, or is a gem that is not installed during the bundle process.

First, the output during the bundle step
```
Step 14 : RUN bundle install --without development test
 ---> Running in e0b9d95942fb
Fetching gem metadata from https://rails-assets.org/...
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rails-assets.org/..
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rails-assets.org/..
Fetching dependency metadata from https://rubygems.org/..
Fetching git://github.com/projectjellyfish/jellyfish-demo.git
Fetching gem metadata from https://rails-assets.org/...
Fetching version metadata from https://rails-assets.org/..
Installing rake 10.5.0
Installing i18n 0.7.0
Using json 1.8.3
Installing minitest 5.8.4
Installing thread_safe 0.3.5
Installing builder 3.2.2
Installing erubis 2.7.0
Installing mini_portile2 2.0.0
Installing rack 1.6.4
Installing mime-types 2.99.1
Installing arel 6.0.3
Installing addressable 2.3.8
Installing thor 0.19.1
Installing concurrent-ruby 1.0.1
Installing tilt 2.0.2
Installing execjs 2.6.0
Installing ice_nine 0.11.2
Installing bcrypt 3.1.11 with native extensions
Installing sass 3.4.22
Installing coffee-script-source 1.10.0
Installing daemons 1.2.3
Installing orm_adapter 0.5.0
Installing unf_ext 0.0.7.2 with native extensions
Installing dotenv 2.1.1
Installing equalizer 0.0.11
Installing hashie 3.4.3
Using bundler 1.11.2
Installing netrc 0.11.0
Installing request_store 1.3.1
Installing pg 0.18.4 with native extensions
Installing puma 3.4.0 with native extensions
Installing rails-assets-angular 1.4.10
Installing rails-assets-api-check 7.5.5
Installing rails-assets-marked 0.3.5
Installing rails-assets-jquery 2.1.4
Installing rails-assets-tinycolor 1.3.0
Installing rails-assets-highcharts 4.1.10
Installing rails-assets-highcharts-ng 0.0.11
Installing rails-assets-lodash 3.10.1
Installing rails-assets-moment 2.10.6
Installing rails_serve_static_assets 0.0.5
Installing rails_stdout_logging 0.0.5
Installing rufus-scheduler 3.2.0
Installing will_paginate 3.0.7
Installing wisper 1.6.1
Installing faker 1.6.3
Installing apipie-rails 0.3.3
Installing tzinfo 1.2.2
Installing descendants_tracker 0.0.4
Installing nokogiri 1.6.7.2 with native extensions
Installing rack-test 0.6.3
Installing warden 1.2.6
Installing mail 2.6.4
Installing json-schema 2.6.1
Installing sprockets 3.6.0
Installing autoprefixer-rails 6.3.6
Installing uglifier 3.0.0
Installing coffee-script 2.4.1
Installing unf 0.1.4
Installing omniauth 1.3.1
Installing rails-assets-angular-animate 1.4.10
Installing rails-assets-angular-aria 1.4.10
Installing rails-assets-angular-bootstrap 0.13.4
Installing rails-assets-angular-filter 0.5.8
Installing rails-assets-angular-messages 1.4.10
Installing rails-assets-angular-resource 1.4.10
Installing rails-assets-angular-sanitize 1.4.10
Installing rails-assets-angular-smart-table 2.1.8
Installing rails-assets-angular-ui-router 0.2.18
Installing rails-assets-ngDraggable 0.1.8
Installing rails-assets-angular-formly 7.1.2
Installing rails-assets-angular-marked 1.0.1
Installing rails-assets-jquery-ui 1.11.4
Installing rails-assets-bootstrap-sass-official 3.3.6
Installing rails-assets-toastr 2.1.2
Installing rails-assets-angularjs-color-picker 1.0.5
Installing rails_12factor 0.0.3
Installing activesupport 4.2.6
Installing axiom-types 0.1.1
Installing coercible 1.0.0
Installing loofah 2.0.3
Installing bootstrap-sass 3.3.6
Installing domain_name 0.5.20160310
Installing rails-assets-angular-ui-sortable 0.13.4
Installing rails-deprecated_sanitizer 1.0.3
Installing globalid 0.3.6
Installing activemodel 4.2.6
Installing activesupport-json_encoder 1.1.0
Installing delayed_job 4.1.1
Installing pundit 1.1.0
Installing virtus 1.0.5
Installing rails-html-sanitizer 1.0.3
Installing http-cookie 1.0.2
Installing rails-dom-testing 1.0.7
Installing activejob 4.2.6
Installing active_model_serializers 0.8.3
Installing activerecord 4.2.6
Installing rest-client 1.8.0
Installing actionview 4.2.6
Installing activerecord-nulldb-adapter 0.3.2
Installing activerecord_json_validator 1.0.0
Installing acts-as-taggable-on 3.5.0
Installing acts_as_list 0.7.4
Installing delayed_job_active_record 4.1.0
Installing friendly_id 5.1.0
Installing paper_trail 4.1.0
Installing paranoia 2.1.5
Installing pg_search 0.7.9
Installing actionpack 4.2.6
Installing actionmailer 4.2.6
Installing railties 4.2.6
Installing has_scope 0.7.0
Installing sprockets-rails 3.0.4
Installing angular-rails-templates 1.0.0
Installing coffee-rails 4.1.1
Installing responders 2.1.2
Installing dotenv-rails 2.1.1
Installing font-awesome-rails 4.6.1.0
Installing time_for_a_boolean 0.1.0
Installing rails 4.2.6
Installing sass-rails 5.0.4
Installing devise 4.0.0
Using jellyfish-demo 0.0.1 from git://github.com/projectjellyfish/jellyfish-demo.git (at master@ee54d58)
Installing ngannotate-rails 1.2.1
Bundle complete! 87 Gemfile dependencies, 124 gems now installed.
Gems in the groups development and test were not installed.
Bundled gems are installed into /usr/local/bundle.
Post-install message from acts-as-taggable-on:
When upgrading

Re-run the migrations generator

    rake acts_as_taggable_on_engine:install:migrations

This will create any new migrations and skip existing ones
Version 3.5.0 has a migration for mysql adapter
```

And then the failing step mentioned above
```
Step 15 : RUN DB_ADAPTER=nulldb bundle exec rake assets:precompile
 ---> Running in 2de57bdcbafc
rake aborted!
Sprockets::FileNotFound: couldn't find file 'angular-color-picker/angularjs-color-picker' with type 'application/javascript'
/api/app/assets/javascripts/libraries.js:24
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/resolve.rb:64:in `resolve!'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/directive_processor.rb:399:in `resolve'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/directive_processor.rb:207:in `process_require_directive'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/directive_processor.rb:180:in `block in process_directives'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/directive_processor.rb:178:in `each'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/directive_processor.rb:178:in `process_directives'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/directive_processor.rb:83:in `_call'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/directive_processor.rb:68:in `call'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/loader.rb:60:in `block in load'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/loader.rb:44:in `load'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/cached_environment.rb:47:in `load'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/bundle.rb:23:in `block in call'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/utils.rb:183:in `dfs'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/bundle.rb:24:in `call'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/loader.rb:60:in `block in load'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/loader.rb:44:in `load'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/cached_environment.rb:47:in `load'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/base.rb:66:in `find_asset'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/manifest.rb:134:in `block in find'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/manifest.rb:133:in `each'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/manifest.rb:133:in `find'
/usr/local/bundle/gems/sprockets-3.6.0/lib/sprockets/manifest.rb:185:in `compile'
/usr/local/bundle/gems/sprockets-rails-3.0.4/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/usr/local/bundle/gems/sprockets-3.6.0/lib/rake/sprocketstask.rb:147:in `with_logger'
/usr/local/bundle/gems/sprockets-rails-3.0.4/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
ERROR: Service 'web' failed to build: The command '/bin/sh -c DB_ADAPTER=nulldb bundle exec rake assets:precompile' returned a non-zero code: 1
```

### Steps to Reproduce (for bugs)

1. Clone Jellyfish repository
2. Run `docker-compose up` from docker terminal inside project directory

### Context

Currently unable to create a Docker container with Project Jellyfish due to this issue.

### Your Environment

* Version used: Latest on `origin/develop`
* Browser Name and version: N/A
* Operating System and version (desktop or mobile): Max OSX

**Comment by chriskacerguis** [comment]
Looks like the library name changed from 'rails-assets-angularjs-color-picker' to 'rails-assets-angular-color-picker'.  I've updated the code.

**Comment by chriskacerguis** [comment]
Hmm...looks like that lib went through all sorts of changes...
