### ISSUE TITLE
jellyfish_app container crashes

### ISSUE THREAD

**Issue by benjfranklin** [boozallen/projectjellyfish#1169]
### Expected Behavior
Running "docker-compose up" should should result in a running container for jellyfish_app

### Current Behavior
Jellyfish_app container stops with "Exit 1"

jellyfish_app | => Booting Puma
jellyfish_app | => Rails 4.2.6 application starting in docker on http://0.0.0.0:3000
jellyfish_app | => Run `rails server -h` for more startup options
jellyfish_app | => Ctrl-C to shutdown server
codelift_db | ERROR:  relation "settings" does not exist at character 323
codelift_db | STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
codelift_db | 	                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
codelift_db | 	                FROM pg_attribute a LEFT JOIN pg_attrdef d
codelift_db | 	                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
codelift_db | 	               WHERE a.attrelid = '"settings"'::regclass
codelift_db | 	                 AND a.attnum > 0 AND NOT a.attisdropped
codelift_db | 	               ORDER BY a.attnum
codelift_db | 	
jellyfish_app | Exiting
jellyfish_app | /usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec': PG::UndefinedTable: ERROR:  relation "settings" does not exist (ActiveRecord::StatementInvalid)
jellyfish_app | LINE 5:                WHERE a.attrelid = '"settings"'::regclass
jellyfish_app |                                           ^
jellyfish_app | :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
jellyfish_app |                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
jellyfish_app |                 FROM pg_attribute a LEFT JOIN pg_attrdef d
jellyfish_app |                   ON a.attrelid = d.adrelid AND a.attnum = d.adnum
jellyfish_app |                WHERE a.attrelid = '"settings"'::regclass
jellyfish_app |                  AND a.attnum > 0 AND NOT a.attisdropped
jellyfish_app |                ORDER BY a.attnum
jellyfish_app | 	from /usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
jellyfish_app | 	from /usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
jellyfish_app | 	from /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
jellyfish_app | 	from /usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
jellyfish_app | 	from /usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
jellyfish_app | 	from /usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
jellyfish_app | 	from /usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
jellyfish_app | 	from /usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:733:in `column_definitions'
jellyfish_app | 	from /usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql/schema_statements.rb:197:in `columns'
jellyfish_app | 	from /usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
jellyfish_app | 	from /usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/attributes.rb:93:in `columns'
jellyfish_app | 	from /usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/attributes.rb:98:in `columns_hash'
jellyfish_app | 	from /usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/relation/query_methods.rb:969:in `block in create_binds'
jellyfish_app | 	from /usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/relation/query_methods.rb:967:in `each'
jellyfish_app | 	from /usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/relation/query_methods.rb:967:in `partition'
jellyfish_app | 	from /usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/relation/query_methods.rb:967:in `create_binds'
jellyfish_app | 	from /usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/relation/query_methods.rb:954:in `build_where'
jellyfish_app | 	from /usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/relation/query_methods.rb:584:in `where!'
jellyfish_app | 	from /usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/relation/query_methods.rb:574:in `where'
jellyfish_app | 	from /usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:84:in `find_by'
jellyfish_app | 	from /usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/querying.rb:7:in `find_by'
jellyfish_app | 	from /usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/core.rb:164:in `find_by'
jellyfish_app | 	from /api/app/models/setting.rb:35:in `block in []'
jellyfish_app | 	from /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/cache.rb:299:in `block in fetch'
jellyfish_app | 	from /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/cache.rb:585:in `block in save_block_result_to_cache'
jellyfish_app | 	from /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/cache.rb:547:in `block in instrument'
jellyfish_app | 	from /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
jellyfish_app | 	from /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/cache.rb:547:in `instrument'
jellyfish_app | 	from /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/cache.rb:584:in `save_block_result_to_cache'
jellyfish_app | 	from /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/cache.rb:299:in `fetch'
jellyfish_app | 	from /api/app/models/setting.rb:34:in `[]'
jellyfish_app | 	from /api/app/mailers/project_mailer.rb:2:in `<class:ProjectMailer>'
jellyfish_app | 	from /api/app/mailers/project_mailer.rb:1:in `<top (required)>'
jellyfish_app | 	from /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
jellyfish_app | 	from /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
jellyfish_app | 	from /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
jellyfish_app | 	from /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
jellyfish_app | 	from /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:360:in `require_or_load'
jellyfish_app | 	from /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:317:in `depend_on'
jellyfish_app | 	from /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:233:in `require_dependency'
jellyfish_app | 	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
jellyfish_app | 	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/engine.rb:471:in `each'
jellyfish_app | 	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/engine.rb:471:in `block in eager_load!'
jellyfish_app | 	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/engine.rb:469:in `each'
jellyfish_app | 	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/engine.rb:469:in `eager_load!'
jellyfish_app | 	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/engine.rb:346:in `eager_load!'
jellyfish_app | 	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/application/finisher.rb:56:in `each'
jellyfish_app | 	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
jellyfish_app | 	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
jellyfish_app | 	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
jellyfish_app | 	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
jellyfish_app | 	from /usr/local/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
jellyfish_app | 	from /usr/local/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
jellyfish_app | 	from /usr/local/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
jellyfish_app | 	from /usr/local/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
jellyfish_app | 	from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each'
jellyfish_app | 	from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `call'
jellyfish_app | 	from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
jellyfish_app | 	from /usr/local/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
jellyfish_app | 	from /usr/local/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
jellyfish_app | 	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
jellyfish_app | 	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
jellyfish_app | 	from /api/config/environment.rb:5:in `<top (required)>'
jellyfish_app | 	from /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
jellyfish_app | 	from /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
jellyfish_app | 	from /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
jellyfish_app | 	from /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
jellyfish_app | 	from /api/config.ru:3:in `block in <main>'
jellyfish_app | 	from /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
jellyfish_app | 	from /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
jellyfish_app | 	from /api/config.ru:in `new'
jellyfish_app | 	from /api/config.ru:in `<main>'
jellyfish_app | 	from /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
jellyfish_app | 	from /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
jellyfish_app | 	from /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
jellyfish_app | 	from /usr/local/bundle/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
jellyfish_app | 	from /usr/local/bundle/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
jellyfish_app | 	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/commands/server.rb:61:in `app'
jellyfish_app | 	from /usr/local/bundle/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
jellyfish_app | 	from /usr/local/bundle/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
jellyfish_app | 	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/commands/server.rb:80:in `start'
jellyfish_app | 	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:80:in `block in server'
jellyfish_app | 	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `tap'
jellyfish_app | 	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `server'
jellyfish_app | 	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
jellyfish_app | 	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
jellyfish_app | 	from bin/rails:9:in `require'
jellyfish_app | 	from bin/rails:9:in `<main>'
jellyfish_app exited with code 1

### Steps to Reproduce (for bugs)

1.  clone git
2. run "docker-compose up"

### Your Environment
* Version used: devel
* Browser Name and version: n/a
* Operating System and version (desktop or mobile): Docker (MacOS)

**Comment by frellnet** [comment]
I have the exact same issue.  Any insight would be helpful.  Thanks!!

Joe
